name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} \
            --build-arg VITE_FEEDBACK_EMAIL=${{ secrets.VITE_FEEDBACK_EMAIL }} \
            -t vsevo1od/from-day-to-day:tapmylink-frontend-${{ github.ref_name }} .

      - name: Push Docker image
        run: |
          docker push vsevo1od/from-day-to-day:tapmylink-frontend-${{ github.ref_name }}
